type FilaArrayObject = (number | null)[];
type ArrayObject = [FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject,
FilaArrayObject];

export default ArrayObject;