type FilaArrayMap = number[];
type ArrayMap = [FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap,
FilaArrayMap];

export default ArrayMap;