type FilaGhostMap = (number | null)[];
type GhostMap = [FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap,
FilaGhostMap];

export default GhostMap;